apiVersion: v1
kind: Service
metadata:
  name: spin
spec:
  ports:
  - port: 8080
  selector:
    app: spin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin
spec:
  selector:
      matchLabels:
          app: spin
  template:
    metadata:
      labels:
        app: spin
    spec:
      containers:
      - name: spin
        image: m1c0l/videoserver_spin:v1
        command: ["java", "-jar", "service.jar"]
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spin-env-file
        volumeMounts:
            - mountPath: /stats/stats_logs
              name: vs-stats
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
#        readinessProbe:
#          httpGet:
#            path: /ping
#            port: 8080
#          initialDelaySeconds: 40
#          periodSeconds: 3
      volumes:
      - name: vs-stats
        hostPath:
            path: /data/vsStats
            type: DirectoryOrCreate
