version: '3'
services:
        vms:
                build: ./videomanagementservice/
                container_name: vms
                hostname: vms
#                ports:
#                - "8082:8080"
                volumes:
                - vsStorage:/Storage       
#                depends_on:
#                - vsDB
#                - nginx
                command: ["./wait-for-it.sh", "vsDB:3306", "--", "java", "-jar", "service.jar"]
                networks:
                - apigw
                - db
                - vpsnet
                                    
        vps:
                build: ./videoprocessingservice/
                container_name: vps
                hostname: vps
#                ports:
#                - "8083:8080"
                volumes:
                - vsStorage:/Storage
#                depends_on:
#                - vms
                networks:
                - vpsnet

        nginx: 
                build: ./nginx/
                container_name: nginx
                hostname: nginx
                ports:
                - "80:80"
                volumes:
                - vsStorage:/Storage
                networks:
                - apigw

        vsDB:
                image: mysql:5.7
                container_name: vsDB
                hostname: vsDB
#                ports:
#                - "3307:3306"
                env_file:
                - ./dbmysql/variables.env
                volumes:
                - ./dbmysql/data_volume:/var/lib/mysql
                networks:
                - db

        vsDBclient:
                build: ./mysqlclient/
                image: videoserver_mpeg-dash_vsdbclient
                container_name: vsDBclient
                hostname: vsDBclient
                command: ["./wait-for-it.sh", "vsDB:3306", "--", "./stats/stats.sh"]
                volumes:
                - vsStats:/app/stats/stats_logs
                networks:
                - db


volumes:
        vsStorage:
        vsStats:


networks:
        apigw:
        db:
        vpsnet:
