apiVersion: v1
data:
  MYSQL_HOST: vs-db
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_HOST":"vs-db"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-01-17T12:48:49Z","name":"vms-env-file","namespace":"default","resourceVersion":"481203","selfLink":"/api/v1/namespaces/default/configmaps/vms-env-file","uid":"22b6e358-5c63-4d5d-a306-051b99079e06"}}
  creationTimestamp: "2020-01-19T15:50:11Z"
  name: vms-env-file
  namespace: default
  resourceVersion: "712752"
  selfLink: /api/v1/namespaces/default/configmaps/vms-env-file
  uid: 9aba4404-d8ca-4971-861d-80a49b2c7dd4
