apiVersion: v1
data:
  MYSQL_DATABASE: videoserverdb
  MYSQL_HOST: vs-db
  MYSQL_PORT: "3306"
  MYSQL_USER: vsuser
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_DATABASE":"videoserverdb","MYSQL_HOST":"vs-db","MYSQL_PORT":"3306","MYSQL_USER":"vsuser"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2020-01-17T12:48:49Z","name":"vs-db-env-file","namespace":"default","resourceVersion":"481204","selfLink":"/api/v1/namespaces/default/configmaps/vs-db-env-file","uid":"a17b648b-2a0e-4c00-ba32-775538ae5f68"}}
  creationTimestamp: "2020-01-19T15:50:11Z"
  name: vs-db-env-file
  namespace: default
  resourceVersion: "712786"
  selfLink: /api/v1/namespaces/default/configmaps/vs-db-env-file
  uid: 1f277be8-0043-4a73-9af3-1a56572c0fc7
